### ISSUE TITLE
API keys leaked in latest commit

### ISSUE THREAD

**Issue by RainbowAsteroids** [DylanHamer/SimpleReddit#1]
It seems like your most recent commit has some API keys in there. Don't know if they're throwaway or not, but it's best to delete and reupload this repo to protect them.

**Comment by DylanHamer** [comment]
I deleted those too. I keep forgetting to remove them so I just delete them
from my Reddit account.

**Comment by RainbowAsteroids** [comment]
That must explain why I can't run the program. Lol
